server:
  port: 1025

#一天跑三次
cron:
  0 0 0/8 * * *

#邮件接收人
mailTo:


spring:
  #邮箱发件人配置
  mail:
    host:
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
        imap:
          ssl:
            socketFactory:
              class:  javax.net.ssl.SSLSocketFactory
              fallback: false
#直接写入cookie
jdCookie:
