server:
  port: 1025

cron:

#邮件接收人
mailTo:

spring:
  #邮箱发件人配置
  mail:
    host:
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#直接写入cookie
jdCookie:
